ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-bookworm AS base
WORKDIR /app

FROM base AS builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-concurrency 1

COPY . .

RUN yarn lerna bootstrap

WORKDIR /app/packages/client
RUN yarn build

FROM base AS runtime

ENV NODE_ENV=production

COPY --from=builder /app /app

WORKDIR /app/packages/client

EXPOSE 3000

CMD ["node", "dist-server/server.js"]
