ARG NODE_VERSION=22

FROM node:$NODE_VERSION-bookworm as base
WORKDIR /app

FROM base as builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-concurrency 1

COPY . .
RUN yarn lerna bootstrap

FROM base as development

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/packages /app/packages
COPY package.json yarn.lock ./

WORKDIR /app/packages/client

EXPOSE 5173
CMD ["yarn", "dev", "--", "--host", "0.0.0.0"]