ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-bookworm AS base
WORKDIR /app

FROM base AS builder

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --network-concurrency 1

WORKDIR /app/packages/server
RUN npm install -g lerna
RUN npx lerna init

RUN yarn build

FROM base AS runtime
ENV NODE_ENV=production
COPY --from=builder /app/packages/server /app/packages/server
WORKDIR /app/packages/server
EXPOSE 3001
CMD ["node", "dist/index.js"]

