ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-bookworm AS builder
WORKDIR /app

COPY package.json yarn.lock lerna.json ./
COPY packages/*/package.json ./packages/

RUN yarn install --frozen-lockfile

COPY packages ./packages

RUN npx lerna run build --scope @app/server


FROM node:${NODE_VERSION}-bookworm AS runtime
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/packages/server ./packages/server

WORKDIR /app/packages/server
EXPOSE 3001
CMD ["node", "dist/index.js"]
